-- 기존 테이블 삭제
--DROP TABLE RESERVATION CASCADE CONSTRAINTS;
--DROP TABLE SALON CASCADE CONSTRAINTS;

-- 미용실 테이블 생성
CREATE TABLE SALON(
    SALON_ID NUMBER(5) PRIMARY KEY,
    SALON_NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(50)
);

-- 예약 테이블 생성
CREATE TABLE RESERVATION(
    RESERVATION_ID NUMBER(5) PRIMARY KEY,
    SALON_ID NUMBER(5) NOT NULL,
    RES_DATE DATE NOT NULL,
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    SERVICE_NAME VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_RES_SALON FOREIGN KEY (SALON_ID)
        REFERENCES SALON(SALON_ID)
);

-- 미용실 데이터 입력
INSERT INTO SALON VALUES (1, '헤어샵A', '02-111-2222', '서울 강남구');
INSERT INTO SALON VALUES (2, '뷰티살롱B', '02-333-4444', '서울 마포구');
INSERT INTO SALON VALUES (3, '스타일샵C', '02-555-6666', '서울 송파구');

-- 예약 데이터 입력
INSERT INTO RESERVATION VALUES (
    1001,
    1,
    TO_DATE('2026-04-15 10:00', 'YYYY-MM-DD HH24:MI'),
    '김민지',
    '커트'
);

INSERT INTO RESERVATION VALUES (
    1002,
    2,
    TO_DATE('2026-04-15 11:00', 'YYYY-MM-DD HH24:MI'),
    '이수연',
    '펌'
);

INSERT INTO RESERVATION VALUES (
    1003,
    1,
    TO_DATE('2026-04-20 14:00', 'YYYY-MM-DD HH24:MI'),
    '박지훈',
    '염색'
);

COMMIT;

-- 확인
SELECT * FROM SALON;
SELECT * FROM RESERVATION;

SELECT S.SALON_NAME, R.CUSTOMER_NAME, R.RES_DATE, R.SERVICE_NAME
FROM SALON S
JOIN RESERVATION R
ON S.SALON_ID = R.SALON_ID;