--교재 165
--ROLLUP()함수

--판매금액 구하기
SELECT * FROM TBL_TEST_ORDER;
SELECT * FROM TBL_TEST_GOODS;
SELECT * FROM TBL_TEST_CUSTOMER;

SELECT C.NAME AS 이름, SUM(O.SALE_CNT * G.PRICE) AS 가격
FROM TBL_TEST_ORDER O
INNER JOIN TBL_TEST_CUSTOMER C
ON C.ID = O.ID
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE
GROUP BY C.NAME;

--ROLLUP
--그룹바이된 결과에 중간집계 구하기 또는  전체집계
SELECT NVL(C.NAME, 'TOTAL') AS 이름, SUM(O.SALE_CNT * G.PRICE) AS 가격
FROM TBL_TEST_ORDER O
INNER JOIN TBL_TEST_CUSTOMER C
ON C.ID = O.ID
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE
GROUP BY ROLLUP(C.NAME);

--고객별 상품별 판매 금액구하기 ( GROUP BY + ROLLUP)
SELECT NVL(C.NAME,'TOTAL'), NVL(G.PNAME, 'SUBTOTAL'),SUM(O.SALE_CNT * G.PRICE)
FROM TBL_TEST_ORDER O
INNER JOIN TBL_TEST_CUSTOMER C
ON C.ID = O.ID
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE
GROUP BY ROLLUP(C.NAME, G.PNAME); --고객별 소개

--교재 167페이지
--부서별,직급별 평균급여, 인원수합 구하기 --GROUP BY
--부서별 합
--전체합
SELECT * FROM EMP;
SELECT DEPTNO,JOB, SAL FROM EMP;

SELECT DEPTNO,JOB, SAL 
FROM EMP 
ORDER BY 1, 2;

--여기까지가 GROUP BY,ROLLUP
SELECT NVL(TO_CHAR(DEPTNO),'TOTAL'),NVL(JOB,'SUBTOTAL'), ROUND(AVG(SAL),1), COUNT(*)
FROM EMP 
GROUP BY ROLLUP(DEPTNO, JOB)
ORDER BY 1, 2;

--교재 205페이지
--SUM() OVER()사용예
SELECT * FROM PANMAE;
SELECT P_DATE, P_TOTAL
FROM PANMAE;

--SUM(P_TOTAL) OVER( ORDER BY P_TOTAL) -- 처음부터 현재행까지의 합계
SELECT P_DATE, P_TOTAL, SUM(P_TOTAL) OVER(ORDER BY P_TOTAL)
FROM PANMAE;
--SUM(P_TOTAL) OVER() -- P_TOTAL 전체합계
SELECT P_DATE, P_TOTAL, SUM(P_TOTAL) OVER()
FROM PANMAE;

--over(
--[partiton  by]
--[order by]
--[range, rows])
SELECT    P_DATE, P_TOTAL ,
     SUM( P_TOTAL)
     OVER(
        ORDER BY P_TOTAL
     )
  FROM  PANMAE;
  
--파티션 나누기
SELECT P_STORE, P_DATE, P_TOTAL ,
     SUM( P_TOTAL)
     OVER(
        PARTITION BY P_STORE
        ORDER BY P_TOTAL
        ROWS between unbounded preceding and current row 
        --RANGE between unbounded preceding and current row --생략이 가능 이게 기본값
     )
FROM  PANMAE;

--SUM(누적할 값이 컬럼명) OVER() 
--[PARTITON BY 컬럼명]
--[ORDER BY 기준컬럼명]
--[RANGE (기본값) || ROWS] BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW

-- EMP 테이블 
SELECT * FROM EMP;
-- SAL(급여) 누적액 구하기
SELECT SUM(SAL) OVER(ORDER BY SAL) AS 누적액 FROM EMP;
-- 직급별 SAL(급여) 누적액 구하기
SELECT ENAME, JOB,SUM(SAL) OVER(PARTITION BY JOB ORDER BY SAL) AS 직급별누적액 FROM EMP;
-- RNAGE, ROWS 변경하기
SELECT ENAME,JOB, SUM(SAL) OVER( ORDER BY SAL RANGE between unbounded preceding and current row)AS RANGESAL FROM EMP;
SELECT ENAME, JOB, SUM(SAL) OVER( ORDER BY SAL ROWS between unbounded preceding and current row) AS ROWSSAL FROM EMP;

--교재 문제풀이
--205페이지
--사용예1
--PANMAE 테이블을 사용하여 1000번 대리점의 판매 내역을 출력하되 판매일자, 제품코드, 판매량, 누적 판매금액을 아래와 같이 출력하세요
SELECT * FROM PANMAE;
SELECT 
    P_DATE, 
    P_CODE, 
    P_QTY, 
    P_TOTAL,SUM(P_TOTAL) OVER(ORDER BY P_TOTAL) AS 누적판매금액 
FROM PANMAE 
WHERE P_STORE = 1000;
--사용예2
--PANMAE 테이블을 사용하여 1000번 대리점의 판매 내역을 제품 코드별로 분류한 후 판매일자, 제품코드, 판매금액, 누적판매금액을 아래와 같이 출력하세요.
SELECT 
    P_DATE, 
    P_CODE, 
    P_QTY, 
    P_TOTAL,
    SUM(P_TOTAL) OVER(PARTITION BY P_CODE ORDER BY P_TOTAL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS 누적판매금액 
FROM PANMAE 
WHERE P_STORE = 1000 ;

--RANK 순위구하기

--DECODE 사용해서 열 집계 만들기 !!
--교재 196 페이지
--RANK() OVER(ORDER BY 컬럼명 ORDER BY 컬ㄹ명)
--RANK() OVER(PARTITION BY 컬럼명, 컬럼명2 ORDERY BY 컬럼명)

--RANK
--DENSE_RANK 

SELECT NAME, POINT, RANK() OVER(ORDER BY POINT DESC)
FROM ACORNTBL;

SELECT NAME, POINT, DENSE_RANK() OVER(ORDER BY POINT DESC)
FROM ACORNTBL;

--EMP
SELECT * FROM EMP;
SELECT JOB, ENAME, SAL,
RANK() OVER(PARTITION BY JOB ORDER BY SAL DESC)
FROM EMP
ORDER BY 1;

--
SELECT * FROM ACORNTBL;
SELECT NAME, 
POINT,RANK() OVER(ORDER BY POINT DESC) AS RANK,
DENSE_RANK() OVER(ORDER BY POINT DESC)AS DENSE_RANK,
ROW_NUMBER() OVER(ORDER BY POINT DESC) AS ROW_NUMBER
FROM ACORNTBL;

SELECT NAME, POINT, RANK() OVER( ORDER BY POINT DESC, BIRTHDAY DESC) AS POINT및BIRTHDAY
FROM ACORNTBL;

--교재 194페이지
--LAG() 함수, LEAD() 함수
--이전행, 다음행

--LAG (컬럼명, 몇번째이전, 기본값)OVER()
--LEAD(컬럼명, 몇번재이후, 기본값)OVER()

--EMP
SELECT * FROM EMP;
SELECT ENAME, SAL FROM EMP;
--LAG
SELECT ENAME, SAL,
LAG(SAL,1,0) OVER(ORDER BY SAL) AS LAG,
LEAD(SAL, 1, 0) OVER( ORDER BY SAL) AS LEAD
FROM EMP;

--전체에 대해서 비율구하기
SELECT NAME, POINT
FROM ACORNTBL;

SELECT NAME, POINT,
SUM(POINT) OVER()
FROM ACORNTBL;

SELECT NAME, POINT,
SUM(POINT) OVER(),
ROUND((POINT/ SUM(POINT) OVER()) * 100,2)
FROM ACORNTBL;

--RATIO_TO_REPORT
SELECT NAME, POINT,
ROUND(RATIO_TO_REPORT(POINT) OVER() * 100 ,2) AS RATIO_TO_REPORT
FROM ACORNTBL;

--EMP
SELECT ENAME, SAL FROM EMP;

SELECT ENAME, SAL,
ROUND(RATIO_TO_REPORT(SAL) OVER() * 100,2)|| '%' AS RATIO_TO_REPORT,
CONCAT(ROUND(RATIO_TO_REPORT(SAL) OVER() * 100,2), '%') AS CONCAT
FROM EMP;

--DECODE 열 집계 구하기
--교재 189페이지
--직급별 사원의 수 구하기 (DECODE 사용하기)
-- CLERK MANAGER PRESIDENT ANALYST SALESMAN
--   3      2        5        0       3
SELECT * FROM EMP;
SELECT ENAME,JOB FROM EMP;
SELECT JOB FROM EMP;
SELECT COUNT(JOB) FROM EMP;
--CLERK 수 구하기
SELECT JOB, DECODE(JOB,'CLERK','*') FROM EMP;
SELECT COUNT(JOB) ,COUNT(DECODE(JOB,'MANAGER','*'))FROM EMP;
SELECT JOB, DECODE(JOB, 'MANAGER', '*') FROM EMP;

SELECT COUNT(DECODE(JOB, 'CLERK', 1)) AS CLERK,
       COUNT(DECODE(JOB, 'MANAGER',1)) AS MANAGER,
       COUNT(DECODE(JOB, 'PRESIDENT',1)) AS PRESIDENT,
       COUNT(DECODE(JOB, 'ANALYST', 1)) AS ANALYST,
       COUNT(DECODE(JOB, 'SALESMAN', 1)) AS SALESMAN
FROM EMP;

SELECT  DEPTNO ,JOB
 FROM EMP;
 
 SELECT  DEPTNO , DECODE(JOB ,'CLERK',9)
 FROM EMP;
 
 SELECT DEPTNO,
       COUNT(DECODE(JOB, 'CLERK', 9))     AS CLERK,
       COUNT(DECODE(JOB, 'SALESMAN', 9))  AS SALESMAN,
       COUNT(DECODE(JOB, 'MANAGER', 9))   AS MANAGER,
       COUNT(DECODE(JOB, 'PRESIDENT', 9)) AS PRESIDENT,
       COUNT(DECODE(JOB, 'ANALYST', 9))   AS ANALYST
FROM EMP
GROUP BY DEPTNO
ORDER BY 1;

--직급별 사원의 수 구하기 (DECODE 사용하기)
--  CLERK MANAGER PRESIDENT ANALYST SALESMAN
--10  1      1        1        0       1
--20  1      1        4        0       2
--30  1      1        0        0       0
SELECT DEPTNO,
       COUNT(DECODE(JOB, 'CLERK', 1)) AS CLERK,
       COUNT(DECODE(JOB, 'MANAGER', 1)) AS MANAGER,
       COUNT(DECODE(JOB, 'PRESIDENT', 1)) AS PRESIDENT,
       COUNT(DECODE(JOB, 'ANALYST', 1)) AS ANALYST,
       COUNT(DECODE(JOB, 'SALESMAN', 1)) AS SALESMAN
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--PIVOT
SELECT * FROM(SELECT DEPTNO, JOB, EMPNO FROM EMP)
PIVOT(
    COUNT(EMPNO)
    FOR JOB
    IN('CLERK' AS "CLERK", 'MANAGER' AS "MANAGER",'SALESMAN' AS "SALESMAN",'ANALYST' AS "ANALYST",'PRESIDENT' AS "PRESIDENT")
);

--교재 192페이지, 193페이지
CREATE TABLE TESTPIVOT AS 
SELECT * FROM(SELECT DEPTNO, JOB, EMPNO FROM EMP)
PIVOT(
    COUNT(EMPNO)
    FOR JOB
    IN('CLERK' AS "CLERK", 'MANAGER' AS "MANAGER",'SALESMAN' AS "SALESMAN",'ANALYST' AS "ANALYST",'PRESIDENT' AS "PRESIDENT")
);
SELECT * FROM TESTPIVOT;

--UNPIVOT
SELECT * FROM TESTPIVOT
UNPIVOT(
    ENPNO
    FOR JOB IN(CLERK,MANAGER,SALESMAN,ANALYST,PRESIDENT)
);

--조인쿼리 실습 이어서 하기(각자 제출하기)
--교재 연습문제 풀기
--210, 211, 212, 213
