CREATE TABLE ACTOR (
    ACTOR_ID VARCHAR2(50) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    GENDER CHAR(1)
);
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (1, '강', '동원',  'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (2, '손', '예진',  'F');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (3, '이', '병헌',  'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (4, '전', '도연',  'F');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (5, '변', '우석',  'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME,  GENDER) VALUES (6, '배', '수지',  'F');


COMMIT;

--###  mysql
CREATE TABLE ACTOR (
    ACTOR_ID VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    GENDER CHAR(1)
);

INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('1', '강', '동원', 'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('2', '손', '예진', 'F');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('3', '이', '병헌', 'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('4', '전', '도연', 'F');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('5', '변', '우석', 'M');
INSERT INTO ACTOR (ACTOR_ID, FIRST_NAME, LAST_NAME, GENDER) VALUES ('6', '배', '수지', 'F');


SELECT * FROM ACTOR;