--교재 400페이지
--뷰,서브쿼리

SELECT * FROM ACORNTBL;
SELECT NAME, POINT FROM ACORNTBL;

SELECT NAME, POINT, SUM(POINT) OVER()
FROM ACORNTBL;

SELECT NAME, POINT, SUM(POINT) OVER(ORDER BY POINT) --RANGE BETWEEN
FROM ACORNTBL;

SELECT NAME, 
    POINT, 
    SUM(POINT) OVER(
    --[PARTITION BY]
        ORDER BY POINT
        --[RANGE(기본값) | ROWS  BETWEEN  UNBOUNDED PRECEDING  AND  CURRENT ROW]
        ROWS  BETWEEN  UNBOUNDED PRECEDING  AND  CURRENT ROW) AS TOTAL
FROM ACORNTBL;

SELECT * FROM EMP;
SELECT DEPTNO, ENAME, SAL FROM EMP;

SELECT DEPTNO, ENAME, SAL, 
        SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) AS PARTITON
FROM EMP;