--1
--EMP
SELECT * FROM EMP;

SELECT SAL, COMM
FROM EMP;

SELECT SAL + COMM
FROM EMP;

SELECT SAL + NVL(COMM,0)
FROM EMP;

SELECT MAX(SAL + NVL(COMM,0))
FROM EMP;

SELECT 
    MAX(SAL + NVL(COMM,0)) AS 최대값,
    MIN(SAL + NVL(COMM,0)) AS 최소값,
    ROUND(AVG(SAL + NVL(COMM,0)), 1) AS 평균
FROM EMP;

--2 STUDENT
DESC STUDENT; --스크립트 출력 

SELECT * FROM STUDENT; --인스턴스 출력 

SELECT BIRTHDAY FROM STUDENT;

SELECT TO_CHAR(BIRTHDAY, 'MM') FROM STUDENT;

--1월 생들만 표시되게 하기
SELECT BIRTHDAY, DECODE(TO_CHAR(BIRTHDAY,'MM'), '01', 8) AS 생일
FROM STUDENT;

SELECT COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '01', 8)) AS 생일
FROM STUDENT;

SELECT COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '01', 8)) AS 생일
FROM STUDENT;

SELECT 
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '01', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '02', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '03', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '04', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '05', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '06', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '07', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '08', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '09', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '10', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '11', 8)) AS 생일,
COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'), '12', 8)) AS 생일
FROM STUDENT;

--3 STUDENT
SELECT * FROM STUDENT;
SELECT TEL FROM STUDENT;
---서울 학생수 구하기
SELECT SUBSTR(TEL, 1, 2) FROM STUDENT;
SELECT 
    COUNT(*) AS TOTAL,
    COUNT(DECODE(SUBSTR(TEL,1,2),'02',9)) AS SEOUL,
    COUNT(DECODE(SUBSTR(TEL,1,3),'031',9)) AS GYEONGGL,
    COUNT(DECODE(SUBSTR(TEL,1,3),'051',9)) AS BUSAN,
    COUNT(DECODE(SUBSTR(TEL,1,3),'052',9)) AS ULSAN,
    COUNT(DECODE(SUBSTR(TEL,1,3),'053',9)) AS DAEGU,
    COUNT(DECODE(SUBSTR(TEL,1,3),'055',9)) AS GYEONGNAM
FROM STUDENT;

--INTSTR
--SELECT 
--COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL,')')-1),'02',8) AS SEOUL
--FROM STUDENT;

--4
INSERT INTO EMP (EMPNO, DEPTNO, ENAME, SAL) VALUES(1000,10,'Tiger',3600);
INSERT INTO EMP (EMPNO, DEPTNO, ENAME, SAL) VALUES(2000,10,'Cat',3000);
COMMIT;
--부서별 급여합 구하기(CLERK)
SELECT * FROM EMP;

SELECT DEPTNO, JOB, SAL FROM EMP;

SELECT JOB, SAL FROM EMP;

SELECT 
JOB,DECODE(JOB,'CLERK',SAL,0)
FROM EMP;
--
SELECT SUM(DECODE(JOB, 'CLERK', SAL, 0)) FROM EMP;

SELECT DEPTNO,
    DECODE(JOB,'CLERK', SAL, 0),
    DECODE(JOB,'MANAGER', SAL, 0),
    DECODE(JOB,'PRESIDENT', SAL, 0),
    DECODE(JOB,'ANALYST', SAL, 0),
    DECODE(JOB,'SALESMAN', SAL, 0)
FROM EMP
ORDER BY 1;

SELECT DEPTNO,
    SUM(DECODE(JOB,'CLERK', SAL, 0)),
    SUM(DECODE(JOB,'MANAGER', SAL, 0)),
    SUM(DECODE(JOB,'PRESIDENT', SAL, 0)),
    SUM(DECODE(JOB,'ANALYST', SAL, 0)),
    SUM(DECODE(JOB,'SALESMAN', SAL, 0)),
    SUM(NVL2(JOB,SAL,0))
FROM EMP
GROUP BY DEPTNO
ORDER BY 1;

--TOTAL
SELECT JOB,SAL FROM EMP;

SELECT SUM(SAL) FROM EMP;

SELECT JOB, SAL, NVL2(JOB,SAL, 0) FROM EMP;

SELECT SUM(NVL2(JOB, SAL, 0 )) FROM EMP;

CREATE TABLE t_emp
(
eid VARCHAR2(13) NOT NULL PRIMARY KEY ,
ename VARCHAR2(20) ,
salary NUMBER(5) ,
deptno NUMBER(5) ,
comm NUMBER(5)
);
COMMIT;
INSERT INTO t_emp VALUES ('e001' , '신동엽' , 280,10,100) ;
INSERT INTO t_emp VALUES ('e002' , '유재석' , 250,20,50) ;
INSERT INTO t_emp VALUES ('e003' , '전현무' , 190,30,0) ;
INSERT INTO t_emp VALUES ('e004' , '양세영' , 300,20,0) ;
INSERT INTO t_emp VALUES ('e005' , '양세찬' , 290,40,100) ;
CREATE TABLE t_dept
(
deptno NUMBER(5) NOT NULL PRIMARY KEY ,
dname VARCHAR2(20)
);
COMMIT;
INSERT INTO t_dept VALUES (10 , '영업팀') ;
INSERT INTO t_dept VALUES (20 , '기획팀') ;
INSERT INTO t_dept VALUES (30 , '관리팀') ;
INSERT INTO t_dept VALUES (40 , '마케팅팀') ;
INSERT INTO t_dept VALUES (50 , '재무팀') ;
COMMIT;

SELECT * FROM T_EMP;
SELECT * FROM T_DEPT;


--VIEW의 목적
--보안과 사용자 편의성
--불필요한 정보를 제공하지 않는다
--복잡한 쿼리를 매번 작성하지 않는다 

--뷰
--단순, 복합, 인라인 뷰

--뷰 만들기
--CREATE VIEW 뷰 이름

CREATE VIEW T_VIEW
AS 
    SELECT ENAME, DEPTNO
    FROM T_EMP;

SELECT * FROM T_VIEW; -- 단순뷰

--복합 뷰 
--조인쿼리를 뷰로 만들기
SELECT * FROM T_EMP;
SELECT * FROM T_DEPT;

SELECT * 
FROM T_EMP E
JOIN T_DEPT D
ON E.DEPTNO = D.DEPTNO;

--원하는 조인 쿼리 완성
SELECT E.ENAME, E.SALARY, D.DNAME 
FROM T_EMP E
JOIN T_DEPT D
ON E.DEPTNO = D.DEPTNO;

--뷰로 만들기
CREATE VIEW V_EMP_DEPT
AS 
SELECT E.ENAME, E.SALARY, D.DNAME 
FROM T_EMP E
JOIN T_DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT * FROM V_EMP_DEPT;

--뷰삭제 방법
DROP VIEW V_EMP_DEPT;

--뷰사용해보기(에이콘 에서 조회하기 - 상품별 판매수량 조회하기
--뷰 경험하기

SELECT * FROM TBL_TEST_CUSTOMER;
SELECT * FROM TBL_TEST_GOODS;
SELECT * FROM TBL_TEST_ORDER;

--상품별 판매수량 조회하기
SELECT O.PCODE, G.PNAME, O.SALE_CNT
FROM TBL_TEST_ORDER O
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE;
--그룹바이 전단계 만들기
SELECT O.PCODE, G.PNAME, SUM(SALE_CNT)
FROM TBL_TEST_ORDER O
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE
GROUP BY O.PCODE, G.PNAME;


CREATE VIEW V_ORDER 
AS 
--그룹바이 전단계 만들기
SELECT O.PCODE, G.PNAME, SUM(SALE_CNT) AS TOTAL
FROM TBL_TEST_ORDER O
JOIN TBL_TEST_GOODS G
ON O.PCODE = G.PCODE
GROUP BY O.PCODE, G.PNAME;

SELECT * FROM V_ORDER;

--뷰의 종료 
--단순뷰 
--복합뷰
--인라인 뷰(FROM 절 뒤에 뷰가 올 수 있음, 임시로 만들어지는 뷰 : 서브쿼리의 종류)

--서브쿼리란? 쿼리안에 쿼리가 있는 형태
--바깥쿼리 : 메인쿼리
--안에 있는 쿼리 : 서브 쿼리
--서브쿼리 오는 위치
--    - FROM 절 뒤(인라인 뷰)
--    - WHERE 절 뒤
--        - 서브쿼리의 결과에 따라
--        - 단일행, 단일컬럼
--        - 복수행, 단일컬럼
--    - SELECT 절 뒤 ( 스칼라 서브 쿼리)

--신동엽 사원보다 급여가 많은 사람 이름 조회하시오
SELECT * FROM T_EMP;

SELECT SALARY FROM T_EMP
WHERE ENAME = '신동엽';


SELECT ENAME, SALARY FROM T_EMP
WHERE SALARY>280;

SELECT ENAME FROM T_EMP
WHERE SALARY>280;

--서브쿼리 사용
--두 개의 쿼리 합체하기

--연관서브쿼리 : 서브쿼리에서 메인쿼리의 내용을 사용하는 거
--비연관서브쿼리 : 서브쿼리 단독으로 사용하는 거
SELECT ENAME FROM T_EMP
WHERE SALARY > (
        SELECT SALARY FROM T_EMP
        WHERE ENAME = '신동엽');

--에이콘테이블
SELECT * FROM ACORNTBL;

--가장 어린 사람의 이름 조회하기
SELECT NAME FROM ACORNTBL
WHERE BIRTHDAY = '05/01/25';

--생일이 가장 큰 사람 MAX(BIRTHDAY)
SELECT MAX(BIRTHDAY) FROM ACORNTBL;

--합체(서브쿼리)
SELECT NAME FROM ACORNTBL
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY) FROM ACORNTBL);
    
--단일행 서브쿼리
--서브쿼리의 결과가 단일행, 단일컬럼( 서브쿼리의 결과가 값 하나일 때)
--단일행 서브쿼리 연산 =, >, < ,>=, <= 연산자 사용가능하다
--문제)
SELECT * FROM ACORNTBL;
--ACORNTBL 테이블에서 포인트가 가장 높은 사람의 이름 조회하시오 -- 김민정
SELECT NAME, POINT
FROM ACORNTBL
WHERE POINT= (
SELECT MAX(POINT) FROM ACORNTBL);
--ACORNTBL 테이블에서 포인트의 평균보다 이상인 사람의 이름 조회하시오 -- 황스일
SELECT NAME, POINT FROM ACORNTBL
WHERE POINT >=(
SELECT AVG(POINT)
FROM ACORNTBL);
--EMP테이블에서 가장 높은 급여를 받는 사람의 이름을 조회하시오 -- 이현겸
SELECT * FROM EMP;
SELECT ENAME FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

--교재429페이지
--연습문제1
---STUDENT 테이블과 DEPARTMENT 테이블을 사용하여'ANTHONYHOPKINS'학생과 1전공 (DEPTNO1)
---이동일한 학생들의 이름과 1전공 이름을 출력하시오
SELECT S.NAME AS STUD_NAME, D.DNAME AS DEPT_NAME
FROM STUDENT S
JOIN DEPARTMENT D
ON S.DEPTNO1 = D.DEPTNO
WHERE S.DEPTNO1 = (
    SELECT DEPTNO1 FROM STUDENT WHERE NAME = 'Anthony Hopkins'
);

--연습문제2
---Professor 테이블과 department 테이블을 조회하여 'Meg Ryan'교수보다 나중에 입사한 사람의 이름과 입사일, 학과명을 출력하시오
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

select P.NAME as PRPOF_NAME, 
SUBSTR(TO_CHAR(P.HIREDATE, 'YYYY-MM-DD'), 1, 10) AS HIREDATE, 
D.DNAME AS DEPT_NAME 
from Professor P
join department D
ON P.DEPTNO = D.DEPTNO
WHERE P.HIREDATE > (
    SELECT HIREDATE FROM PROFESSOR WHERE NAME = 'Meg Ryan'
);

--FROM절 뒤에 나오는 서브쿼리(인라인 뷰 : 임시뷰로 만들어짐!!
--사용예시
--에이콘몰
SELECT * FROM TBL_TEST_ORDER;
SELECT * FROM TBL_TEST_CUSTOMER;
SELECT * FROM TBL_TEST_GOODS;

--고객별 판매수량 합계 조회하기
--송주창 9 
--여도현 6
--김재민 2
--이정하 5
--장해든 3

--그룹바이 전 단계 만들기
SELECT C.NAME, O.SALE_CNT
FROM TBL_TEST_ORDER O
JOIN TBL_TEST_CUSTOMER C
ON O.ID = C.ID;

SELECT C.NAME, SUM(O.SALE_CNT) AS SUM
FROM TBL_TEST_ORDER O
JOIN TBL_TEST_CUSTOMER C
ON O.ID = C.ID
GROUP BY C.NAME
ORDER BY 2 DESC;

--FROM절 뒤에 서브쿼리
--1) 고객코드별 판매수량 합 구하기(주문테이블)
--2)위의 쿼리내용과 고객테이블을 조인하여 쿼리 완성하기
SELECT ID,SALE_CNT
FROM TBL_TEST_ORDER;

--1)
SELECT ID,SUM(SALE_CNT)
FROM TBL_TEST_ORDER
GROUP BY ID;

--2)
SELECT C.NAME, A.CNT
FROM (
    SELECT ID,SUM(SALE_CNT) AS CNT
    FROM TBL_TEST_ORDER
    GROUP BY ID) A
    JOIN TBL_TEST_CUSTOMER C
    ON A.ID = C.ID;
    
--**다중행 서브쿼리 (교재 430페이지)**
--- WHERE절 뒤에 나오는 서브쿼리
--- 다중행 사용가능 연산자
--    - IN, >ANY, <ANY, >ALL , <ALL, EXISTS
SELECT * FROM EMP2;

SELECT EMPNO, NAME DEPTNO FROM EMP2;
SELECT DCODE, AREA FROM DEPT2 WHERE AREA = 'Pohang Main Office';

SELECT EMPNO, NAME, DEPTNO 
FROM EMP2
WHERE DEPTNO IN('0001', '1003', '1006', '1007');

SELECT EMPNO, NAME, DEPTNO
FROM EMP2
WHERE DEPTNO IN( 
        SELECT DCODE
        FROM DEPT2 
        WHERE AREA = 'Pohang Main Office');

SELECT ENAME, SAL
FROM EMP
WHERE SAL> ANY(
    SELECT SAL
    FROM EMP
    WHERE DEPTNO = 20
);

SELECT ENAME, SAL
FROM EMP
WHERE SAL> ALL(
    SELECT SAL
    FROM EMP
    WHERE DEPTNO = 20
);

--EXISTS 페이지 432
--잘못된예
SELECT * FROM T_EMP;
SELECT * 
FROM T_EMP 
WHERE EXISTS (
    SELECT DEPTNO FROM T_DEPT WHERE DEPTNO = 70
);

--EXISTS 잘 된 예
SELECT * FROM T_EMP;
SELECT * 
FROM T_EMP 
WHERE EXISTS (
    SELECT DEPTNO FROM T_DEPT WHERE DEPTNO = 10
);

--## 연관서브쿼리, 비연관서브쿼리
--연관서브쿼리
--자신의 부서의 평균보다 높은 사람 조회하기
SELECT * FROM EMP;

SELECT * FROM EMP E
WHERE E.SAL > (
    SELECT AVG(E2.SAL)
    FROM EMP E2
    WHERE E2.DEPTNO = E.DEPTNO
--    WHERE E2.DEPTNO = 10
);

--- 연관서브쿼리 실행순서
--    1. 메인쿼리의 값이 서브쿼리에 전달
--    2. 서브쿼리실행
--    3. 메인쿼리에서 사용함
--    4. 조건에 맞으면 결과에 나옴

--## 스칼라서브쿼리 (SELECT 절)
--단일행, 단일컬럼
SELECT * FROM EMP;
--부서이름 가져오기를 스칼라서브쿼리
SELECT E.ENAME, E.DEPTNO,(SELECT D.DNAME FROM DEPT D WHERE D.DEPTNO = E.DEPTNO) AS 부서이름 
FROM EMP E;

--**SQL : 사용자** 
--- DMBS(오라클) 소통언어
--**DDL** 
--- CREATE, DROP, ALTER
--**DML** 
--- READ(SELECT), INSERT, UPDATE, DELETE
--**DCL** 
--- GRANT, REVOKE

--데이터조회하기
--데이터 추가하기
--데이터 변경하기
--데이터 삭제하기

--ACORNTBL
DESC ACORNTBL;

SELECT * FROM ACORNTBL;
--데이터 추가하기
INSERT INTO ACORNTBL(ID, PW, NAME, POINT) VALUES('KING', '3163','김우석',9999);
INSERT INTO ACORNTBL(ID, PW, NAME, POINT) VALUES('SHJ', '5728','오혜원',99999);
COMMIT;
--데이터 변경하기
UPDATE ACORNTBL
SET NAME = '김석진'
WHERE ID = 'SHJ';
COMMIT;
--데이터 삭제하기
SELECT * FROM ACORNTBL;
DELETE
FROM ACORNTBL
WHERE ID = 'SHJ';
commit;